"""initial schema

Revision ID: f1bcf55f7bc6
Revises: 
Create Date: 2026-09-09 12:01:08.687482
"""
from alembic import op
import sqlalchemy as sa

import easyem.db
from sqlalchemy.dialects import postgresql

revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('type', sa.Enum('personal', 'organization', name='account_type'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', easyem.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', easyem.db.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('waitlist_entries',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('context', sa.String(length=2000), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('created_at', easyem.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('contacted_at', easyem.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('webhook_events',
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_event_id', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload_raw', sa.String(), nullable=False),
    sa.Column('signature_verified', sa.Boolean(), nullable=False),
    sa.Column('received_at', easyem.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('processed_at', easyem.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_webhook_provider_event')
    )
    op.create_table('credit_wallets',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', easyem.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', easyem.db.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('balance >= 0', name='ck_wallet_balance_non_negative'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email_verified_at', easyem.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', 'deleted', name='user_status'), nullable=False),
    sa.Column('default_account_id', sa.Uuid(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret_encrypted', sa.String(length=512), nullable=True),
    sa.Column('terms_version_accepted', sa.String(length=32), nullable=True),
    sa.Column('terms_accepted_at', easyem.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('marketing_consent', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', easyem.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', easyem.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', easyem.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', easyem.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', easyem.db.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['default_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('credit_transactions',
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.Column('operation', sa.Enum('grant', 'purchase', 'reserve', 'release', 'consume', 'refund', 'adjustment', name='ledger_op'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('reference_type', sa.String(length=40), nullable=True),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.String(length=400), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', easyem.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('amount <> 0', name='ck_credit_tx_amount_nonzero'),
    sa.ForeignKeyConstraint(['wallet_id'], ['credit_wallets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_credit_tx_idempotency')
    )
    op.create_index(op.f('ix_credit_transactions_wallet_id'), 'credit_transactions', ['wallet_id'], unique=False)
    op.create_index('ix_credit_tx_reference', 'credit_transactions', ['reference_type', 'reference_id'], unique=False)
    op.create_index('ix_credit_tx_wallet_created', 'credit_transactions', ['wallet_id', 'created_at'], unique=False)
    op.create_table('memberships',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', 'viewer', name='membership_role'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', easyem.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', easyem.db.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'user_id', name='uq_membership_account_user')
    )
    op.create_index(op.f('ix_memberships_account_id'), 'memberships', ['account_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', 'deleted', name='project_status', native_enum=False, length=20), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('archived_at', easyem.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', easyem.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', easyem.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', easyem.db.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_account_id'), 'projects', ['account_id'], unique=False)
    op.create_index('ix_projects_account_status', 'projects', ['account_id', 'status'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', easyem.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', easyem.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('used_at', easyem.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', easyem.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_family', 'sessions', ['family_id'], unique=False)
    op.create_index(op.f('ix_sessions_refresh_token_hash'), 'sessions', ['refresh_token_hash'], unique=True)
    op.create_index('ix_sessions_user_active', 'sessions', ['user_id', 'revoked_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('verification_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.Enum('email_verification', 'password_reset', name='token_purpose'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', easyem.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', easyem.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', easyem.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_tokens_token_hash'), 'verification_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_verification_tokens_user_id'), 'verification_tokens', ['user_id'], unique=False)
    op.create_table('credit_reservations',
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('status', sa.Enum('held', 'settled', 'released', 'expired', name='reservation_status'), nullable=False),
    sa.Column('reference_type', sa.String(length=40), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=False),
    sa.Column('reserve_tx_id', sa.Uuid(), nullable=False),
    sa.Column('consume_tx_id', sa.Uuid(), nullable=True),
    sa.Column('release_tx_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', easyem.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', easyem.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', easyem.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['consume_tx_id'], ['credit_transactions.id'], ),
    sa.ForeignKeyConstraint(['release_tx_id'], ['credit_transactions.id'], ),
    sa.ForeignKeyConstraint(['reserve_tx_id'], ['credit_transactions.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['credit_wallets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_type', 'reference_id', name='uq_reservation_reference')
    )
    op.create_index(op.f('ix_credit_reservations_wallet_id'), 'credit_reservations', ['wallet_id'], unique=False)
    op.create_index('ix_reservation_expiry', 'credit_reservations', ['status', 'expires_at'], unique=False)
    op.create_table('project_versions',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('definition', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('content_hash', sa.String(length=71), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_report', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('change_summary', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', easyem.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version_number', name='uq_version_number')
    )
    op.create_index('ix_project_versions_hash', 'project_versions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_project_versions_project_id'), 'project_versions', ['project_id'], unique=False)
    op.create_table('simulation_jobs',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('project_version_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('execution_status', sa.Enum('pending', 'queued', 'running', 'succeeded', 'failed', 'cancelled', 'timed_out', name='execution_status', native_enum=False, length=16), nullable=False),
    sa.Column('settlement_status', sa.Enum('none', 'reserved', 'settled', 'released', name='settlement_status', native_enum=False, length=16), nullable=False),
    sa.Column('backend', sa.String(length=40), nullable=False),
    sa.Column('backend_version', sa.String(length=40), nullable=True),
    sa.Column('external_job_id', sa.String(length=200), nullable=True),
    sa.Column('content_hash', sa.String(length=71), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('cost_ceiling', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('cost_actual', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('reservation_id', sa.Uuid(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('heartbeat_at', easyem.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('cpu_seconds', sa.Float(), nullable=True),
    sa.Column('peak_memory_mb', sa.Float(), nullable=True),
    sa.Column('cell_count', sa.Integer(), nullable=True),
    sa.Column('created_at', easyem.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('started_at', easyem.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', easyem.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', easyem.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reservation_id'], ['credit_reservations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_job_idempotency')
    )
    op.create_index('ix_jobs_account_created', 'simulation_jobs', ['account_id', 'created_at'], unique=False)
    op.create_index('ix_jobs_execution', 'simulation_jobs', ['execution_status'], unique=False)
    op.create_index('ix_jobs_heartbeat', 'simulation_jobs', ['execution_status', 'heartbeat_at'], unique=False)
    op.create_index(op.f('ix_simulation_jobs_account_id'), 'simulation_jobs', ['account_id'], unique=False)
    op.create_index(op.f('ix_simulation_jobs_content_hash'), 'simulation_jobs', ['content_hash'], unique=False)
    op.create_index(op.f('ix_simulation_jobs_project_id'), 'simulation_jobs', ['project_id'], unique=False)
    op.create_table('job_events',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=True),
    sa.Column('detail', sa.String(length=1000), nullable=True),
    sa.Column('created_at', easyem.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['simulation_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_table('simulation_results',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('artifacts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('demonstration_only', sa.Boolean(), nullable=False),
    sa.Column('created_at', easyem.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['simulation_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_results')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_table('job_events')
    op.drop_index(op.f('ix_simulation_jobs_project_id'), table_name='simulation_jobs')
    op.drop_index(op.f('ix_simulation_jobs_content_hash'), table_name='simulation_jobs')
    op.drop_index(op.f('ix_simulation_jobs_account_id'), table_name='simulation_jobs')
    op.drop_index('ix_jobs_heartbeat', table_name='simulation_jobs')
    op.drop_index('ix_jobs_execution', table_name='simulation_jobs')
    op.drop_index('ix_jobs_account_created', table_name='simulation_jobs')
    op.drop_table('simulation_jobs')
    op.drop_index(op.f('ix_project_versions_project_id'), table_name='project_versions')
    op.drop_index('ix_project_versions_hash', table_name='project_versions')
    op.drop_table('project_versions')
    op.drop_index('ix_reservation_expiry', table_name='credit_reservations')
    op.drop_index(op.f('ix_credit_reservations_wallet_id'), table_name='credit_reservations')
    op.drop_table('credit_reservations')
    op.drop_index(op.f('ix_verification_tokens_user_id'), table_name='verification_tokens')
    op.drop_index(op.f('ix_verification_tokens_token_hash'), table_name='verification_tokens')
    op.drop_table('verification_tokens')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index('ix_sessions_user_active', table_name='sessions')
    op.drop_index(op.f('ix_sessions_refresh_token_hash'), table_name='sessions')
    op.drop_index('ix_sessions_family', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_projects_account_status', table_name='projects')
    op.drop_index(op.f('ix_projects_account_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_account_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index('ix_credit_tx_wallet_created', table_name='credit_transactions')
    op.drop_index('ix_credit_tx_reference', table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_wallet_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('credit_wallets')
    op.drop_table('webhook_events')
    op.drop_table('waitlist_entries')
    op.drop_table('accounts')
    # ### end Alembic commands ###
