"""openEMS run generated by EasyEM. Standalone: read it, edit it, run it.

Requires openEMS (GPL v3) and CSXCAD. EasyEM invokes this file as a separate
process and reads results.json; nothing here is imported into EasyEM.

    python3 run.py <output_directory>
"""

import json
import os
import sys

import numpy as np
from CSXCAD import ContinuousStructure
from openEMS import openEMS
from openEMS.physical_constants import C0, EPS0

OUT = sys.argv[1] if len(sys.argv) > 1 else "."
SIM = os.path.join(OUT, "sim")
UNIT = 1e-3  # all dimensions below are in millimetres

f0 = 2450000000.0
fc = 735000000.0

patch_w = 41.34305502711388
patch_l = 33.097453660949164
sub_w = 46.22105502711388
sub_l = 37.975453660949164
sub_h = 0.813
eps_r = 3.38
tan_d = 0.0027
feed_y = -4.548726830474581
feed_R = 50.0

res = 2.5598995290470143
edge_res = 1.2799497645235072
sub_cells = 4

# Dielectric loss enters openEMS as a conductivity at the design frequency.
kappa = tan_d * 2 * np.pi * f0 * EPS0 * eps_r

FDTD = openEMS(NrTS=41833, EndCriteria=1e-4)
FDTD.SetGaussExcite(f0, fc)
# MUR absorbing boundaries, with the ground plane backing the structure.
FDTD.SetBoundaryCond(["MUR"] * 6)

CSX = ContinuousStructure()
FDTD.SetCSX(CSX)
mesh = CSX.GetGrid()
mesh.SetDeltaUnit(UNIT)

# --- substrate ------------------------------------------------------------
substrate = CSX.AddMaterial("substrate", epsilon=eps_r, kappa=kappa)
substrate.AddBox(
    priority=0,
    start=[-sub_w / 2, -sub_l / 2, 0],
    stop=[sub_w / 2, sub_l / 2, sub_h],
)
# Explicit lines through the substrate: the fringing field sets the resonant
# length, so under-resolving the thickness moves the answer.
mesh.AddLine("z", np.linspace(0, sub_h, sub_cells + 1))

# --- ground plane ---------------------------------------------------------
gnd = CSX.AddMetal("gnd")
gnd.AddBox(
    priority=10,
    start=[-sub_w / 2, -sub_l / 2, 0],
    stop=[sub_w / 2, sub_l / 2, 0],
)

# --- patch ----------------------------------------------------------------
patch = CSX.AddMetal("patch")
patch.AddBox(
    priority=10,
    start=[-patch_w / 2, -patch_l / 2, sub_h],
    stop=[patch_w / 2, patch_l / 2, sub_h],
)
# Thirds rule on the metal edges: the current density is singular there, and a
# symmetric line straddling the edge resolves it badly.
FDTD.AddEdges2Grid(dirs="xy", properties=patch, metal_edge_res=edge_res)
FDTD.AddEdges2Grid(dirs="xy", properties=gnd)

# --- feed -----------------------------------------------------------------
port = FDTD.AddLumpedPort(
    1, feed_R,
    [0, feed_y, 0], [0, feed_y, sub_h],
    "z", 1.0, priority=5, edges2grid="xy",
)

# --- air box and smoothing -----------------------------------------------
lambda0_mm = C0 / f0 / UNIT
margin = lambda0_mm / 4
mesh.AddLine("x", [-sub_w / 2 - margin, sub_w / 2 + margin])
mesh.AddLine("y", [-sub_l / 2 - margin, sub_l / 2 + margin])
mesh.AddLine("z", [-margin, sub_h + margin])
mesh.SmoothMeshLines("all", res, 1.4)

nf2ff = FDTD.CreateNF2FFBox()

progress(0.05, "meshing")
FDTD.Run(SIM, verbose=0, cleanup=True)
progress(0.85, "post-processing")

freq = np.linspace(max(1e6, f0 - fc), f0 + fc, 401)
port.CalcPort(SIM, freq)

s11 = port.uf_ref / port.uf_inc
z_in = port.uf_tot / port.if_tot

# Radiation pattern at the frequency of best match, not at the nominal design
# frequency: a fabricated patch resonates where it resonates.
idx = int(np.argmin(np.abs(s11)))
f_res = float(freq[idx])

theta = np.arange(-90, 91, 2.0)
nf = nf2ff.CalcNF2FF(SIM, f_res, theta, [0.0, 90.0], center=[0, 0, sub_h / 2])
e_norm = nf.E_norm[0]
peak = float(np.max(e_norm)) or 1.0
e_plane = 20 * np.log10(np.maximum(e_norm[:, 0] / peak, 1e-5))
h_plane = 20 * np.log10(np.maximum(e_norm[:, 1] / peak, 1e-5))

write({
    "frequencies_hz": freq.tolist(),
    "s_parameters": {
        "S11": [{"re": float(v.real), "im": float(v.imag)} for v in s11]
    },
    "input_impedance_ohm": [
        {"re": float(v.real), "im": float(v.imag)} for v in z_in
    ],
    "radiation_pattern": {
        "theta_deg": theta.tolist(),
        "e_plane_db": e_plane.tolist(),
        "h_plane_db": h_plane.tolist(),
        "peak_directivity_dbi": float(10 * np.log10(nf.Dmax[0])),
    },
    "scalars": {
        "resonant_frequency_hz": f_res,
        "return_loss_db": float(20 * np.log10(abs(s11[idx]))),
        "directivity_dbi": float(10 * np.log10(nf.Dmax[0])),
        "radiated_power_w": float(nf.Prad[0]),
        "patch_width_m": patch_w * UNIT,
        "patch_length_m": patch_l * UNIT,
    },
})
progress(1.0, "done")

def write(payload):
    payload["solver"] = "openEMS"
    with open(os.path.join(OUT, "results.json"), "w") as fh:
        json.dump(payload, fh)


def progress(fraction, message=""):
    """Coarse progress for the platform to poll. openEMS itself reports to
    stdout; this file is what EasyEM watches."""
    with open(os.path.join(OUT, "progress.json"), "w") as fh:
        json.dump({"progress": round(float(fraction) * 100, 1),
                   "message": message}, fh)
